# Generated by Django 4.2.18 on 2025-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
