version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: project1_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: nsdmitrij/project01:latest
    container_name: project1_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    working_dir: /app

volumes:
  postgres_data: