"""remove tokens, added session id

Revision ID: 2cab341f7c55
Revises: a600ed89ba23
Create Date: 2026-01-11 00:37:26.871690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cab341f7c55'
down_revision: Union[str, None] = 'a600ed89ba23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_access_token_key', 'users', type_='unique')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_access_token_key', 'users', ['access_token'])
    # ### end Alembic commands ###
