"""add owner id for book club

Revision ID: 4b4cd74bc50c
Revises: 1dba2ef47ba7
Create Date: 2025-02-23 13:57:19.813301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4cd74bc50c'
down_revision: Union[str, None] = '1dba2ef47ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_table('user_bookclub')
    op.drop_index('ix_book_clubs_id', table_name='book_clubs')
    op.drop_table('book_clubs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_clubs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_clubs_id', 'book_clubs', ['id'], unique=False)
    op.create_table('user_bookclub',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('bookclub_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['bookclub_id'], ['book_clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('access_token', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
