"""add base db model

Revision ID: 938df7213c12
Revises: 67110f641e28
Create Date: 2025-03-28 14:51:19.476784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '938df7213c12'
down_revision: Union[str, None] = '67110f641e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('book_clubs', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_index('ix_book_clubs_id', table_name='book_clubs')
    op.drop_column('book_clubs', 'creation_date')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('book_clubs', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index('ix_book_clubs_id', 'book_clubs', ['id'], unique=False)
    op.drop_column('book_clubs', 'updated_at')
    op.drop_column('book_clubs', 'created_at')
    # ### end Alembic commands ###
