"""prepare user for telegram

Revision ID: a600ed89ba23
Revises: 12d8431be97d
Create Date: 2025-04-03 12:35:25.550657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a600ed89ba23'
down_revision: Union[str, None] = '12d8431be97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('is_telegram_user', sa.Boolean(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'phone_number',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'is_telegram_user')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
