name: Run Tests on PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Postgres with Docker Compose
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Wait for Postgres to be ready
        run: |
          until docker exec $(docker ps -qf "ancestor=postgres:15") pg_isready -U test_admin; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run tests
        env:
          IS_TEST: "true"
          TEST_DATABASE_URL: "postgresql://test_admin:test_password@localhost:5433/test_database"
        run: |
          pytest -v -s

      - name: Shutdown Docker Compose
        if: always()
        run: docker-compose -f docker-compose.test.yml down